spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: payment_user
    password: payment_password


  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092