spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_URL}

server:
  port: ${SERVER_PORT:4000}